# Step 1: Use the official Golang image to build the application
FROM golang:1.23.2 AS builder

# Setp 2: Set the current working directory inside the container
WORKDIR /app 

# Step 3: Copy the go modules and download the dependencies
COPY go.mod go.sum ./
RUN go mod tidy

# Step 4: Copy the rest of the appliscation code into the container
COPY . .

# Step 5: Build the Go application
RUN go build -o server .

# Step 6: Start a new image from scratch (a minimal base image)
FROM alpine:latest

# Step 7: Install dependencies needed to run the server
RUN apk --no-cache add ca-certificates

# Step 8: Copy the built server from the builder image
COPY --from=builder /app/server /usr/local/bin/server

# Step 9: Copy SSL certificates if they exist(.crt and .key)
COPY server.crt /etc/ssl/certs/server.crt
COPY server.key /etc/ssl/private/server.key

# Step 10: Expose the server port (e.g., port 443 for HTTPS)
EXPOSE 443

# Step 11: Command to run the server
CMD ["server"]