# Use a Go base image for building the application
FROM golang:1.23.2 AS builder

# Set the working directory inside the container
WORKDIR /app



# Copy the source code into the container
COPY . .

# Build the Go executable and place it in the /app directory
RUN go build -o /app/smtp-email-server -buildvcs=false

# Start a new image for the final runtime
FROM alpine:latest

# Copy the built executable from the builder stage to the final image
COPY --from=builder /app/smtp-email-server /usr/local/bin/smtp-email-server

# Ensure the executable has permissions to be run
RUN chmod +x /usr/local/bin/smtp-email-server

# Expose the port your server listens on (e.g., port 8080)
EXPOSE 8080

# Command to run the server
CMD ["/usr/local/bin/smtp-email-server"]
